import { AdminLayout } from "@/components/layout/admin-layout";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Card, CardContent } from "@/components/ui/card";
import { FileText, FileArchive, Image as ImageIcon, RotateCcw, CheckCircle, Clock, AlertTriangle, Loader2, AlertCircle, RefreshCw, ExternalLink } from "lucide-react";
import { useAdminListFiles, useAdminRegenerateFile } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { motion } from "framer-motion";
import { formatDate } from "@/lib/utils";

function getFileIcon(type: string) {
  switch (type?.toUpperCase()) {
    case "PDF": return <FileText className="w-4 h-4 text-red-400" />;
    case "ZIP": return <FileArchive className="w-4 h-4 text-blue-400" />;
    case "THUMBNAIL": case "IMAGE": return <ImageIcon className="w-4 h-4 text-purple-400" />;
    default: return <FileText className="w-4 h-4 text-muted-foreground" />;
  }
}

function getStatusBadge(status: string) {
  switch (status?.toUpperCase()) {
    case "READY": return <Badge className="bg-emerald-500/20 text-emerald-400 border-emerald-500/30">Ready</Badge>;
    case "FAILED": return <Badge className="bg-red-500/20 text-red-400 border-red-500/30">Failed</Badge>;
    case "GENERATING": return <Badge className="bg-blue-500/20 text-blue-400 border-blue-500/30"><span className="w-1.5 h-1.5 rounded-full bg-blue-400 animate-pulse mr-1.5 inline-block" />Generating</Badge>;
    case "QUEUED": return <Badge className="bg-amber-500/20 text-amber-400 border-amber-500/30">Queued</Badge>;
    default: return <Badge variant="outline">{status}</Badge>;
  }
}

function formatSize(bytes: number | null) {
  if (!bytes) return "—";
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

export default function FilesPage() {
  const queryClient = useQueryClient();

  const { data: filesData, isLoading, isError, refetch } = useAdminListFiles(
    {},
    { query: { queryKey: ["adminFiles"], refetchInterval: 8000 } }
  );

  const { mutateAsync: regenerate } = useAdminRegenerateFile({
    mutation: {
      onSuccess: () => {
        toast.success("File queued for regeneration");
        queryClient.invalidateQueries({ queryKey: ["adminFiles"] });
      },
      onError: () => toast.error("Failed to queue regeneration"),
    }
  });

  const files = filesData?.files || [];
  const totalFiles = filesData?.total || files.length;
  const readyCount = files.filter((f: any) => f.status === "READY").length;
  const generatingCount = files.filter((f: any) => f.status === "GENERATING" || f.status === "QUEUED").length;
  const failedCount = files.filter((f: any) => f.status === "FAILED").length;

  const stats = [
    { label: "Total Files", value: totalFiles, icon: FileArchive, color: "text-primary" },
    { label: "Ready", value: readyCount, icon: CheckCircle, color: "text-emerald-400" },
    { label: "Generating", value: generatingCount, icon: Clock, color: "text-blue-400" },
    { label: "Failed", value: failedCount, icon: AlertTriangle, color: "text-red-400" },
  ];

  return (
    <AdminLayout>
      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col gap-8 max-w-7xl mx-auto">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-display font-bold">Generated Files</h1>
            <p className="text-muted-foreground mt-1">PDFs, ZIPs, and image assets generated by the system</p>
          </div>
          <Button variant="outline" size="sm" onClick={() => refetch()} className="gap-2">
            <RefreshCw className="w-4 h-4" /> Refresh
          </Button>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {stats.map((s) => (
            <Card key={s.label} className="bg-card border-border">
              <CardContent className="p-5">
                <div className="flex justify-between items-center mb-3">
                  <p className="text-xs font-medium text-muted-foreground">{s.label}</p>
                  <s.icon className={`w-4 h-4 ${s.color}`} />
                </div>
                <p className="text-2xl font-bold">
                  {isLoading ? <span className="text-muted-foreground">—</span> : s.value}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>

        <div className="bg-card border border-border rounded-xl overflow-hidden">
          {isLoading ? (
            <div className="flex items-center justify-center py-16">
              <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
            </div>
          ) : isError ? (
            <div className="flex flex-col items-center justify-center py-16 gap-3">
              <AlertCircle className="w-8 h-8 text-destructive opacity-60" />
              <p className="text-muted-foreground text-sm">Failed to load files</p>
              <Button variant="outline" size="sm" onClick={() => refetch()} className="gap-2">
                <RefreshCw className="w-4 h-4" /> Retry
              </Button>
            </div>
          ) : files.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-16 gap-3">
              <FileArchive className="w-10 h-10 text-muted-foreground opacity-30" />
              <p className="text-muted-foreground text-sm">No generated files yet</p>
              <p className="text-xs text-muted-foreground">Files are created automatically when packs are published</p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow className="border-border hover:bg-transparent">
                  <TableHead>File Type</TableHead>
                  <TableHead>Pack ID</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Size</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {files.map((file: any) => (
                  <TableRow key={file.id} className="border-border">
                    <TableCell>
                      <div className="flex items-center gap-2 font-medium text-sm">
                        {getFileIcon(file.fileType)}
                        {file.fileType}
                      </div>
                    </TableCell>
                    <TableCell className="text-muted-foreground text-sm">Pack #{file.packId}</TableCell>
                    <TableCell>{getStatusBadge(file.status)}</TableCell>
                    <TableCell className="text-muted-foreground font-mono text-xs">{formatSize(file.fileSizeBytes)}</TableCell>
                    <TableCell className="text-muted-foreground text-sm">{formatDate(file.createdAt)}</TableCell>
                    <TableCell className="text-right">
                      <div className="flex items-center justify-end gap-1">
                        {file.publicUrl && (
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 px-2 text-muted-foreground hover:text-primary"
                            onClick={() => window.open(file.publicUrl, "_blank")}
                          >
                            <ExternalLink className="w-4 h-4" />
                          </Button>
                        )}
                        {file.status === "FAILED" && (
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 px-2 text-red-400 hover:text-red-300"
                            onClick={() => regenerate({ id: file.id })}
                          >
                            <RotateCcw className="w-4 h-4 mr-1" /> Retry
                          </Button>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </div>
      </motion.div>
    </AdminLayout>
  );
}
