import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import packsRouter from "./packs.js";
import categoriesRouter from "./categories.js";
import searchRouter from "./search.js";
import userRouter from "./user.js";
import reviewsRouter from "./reviews.js";
import checkoutRouter from "./checkout.js";
import ordersRouter from "./orders.js";
import adminRouter from "./admin.js";
import statsRouter from "./stats.js";
import newsletterRouter from "./newsletter.js";
import profilesRouter from "./profiles.js";
import notificationsRouter from "./notifications.js";
import socialRouter from "./social.js";
import cartRouter from "./cart.js";
import creatorRouter from "./creator.js";
import promptLibraryRouter from "./prompt-library.js";
import subscriptionsRouter from "./subscriptions.js";
import giftsRouter from "./gifts.js";
import messagesRouter from "./messages.js";
import communityRouter from "./community.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(packsRouter);
router.use(categoriesRouter);
router.use(searchRouter);
router.use(userRouter);
router.use(reviewsRouter);
router.use(checkoutRouter);
router.use(ordersRouter);
router.use("/admin", adminRouter);
router.use(statsRouter);
router.use(newsletterRouter);
router.use(profilesRouter);
router.use(notificationsRouter);
router.use(socialRouter);
router.use(cartRouter);
router.use(creatorRouter);
router.use(promptLibraryRouter);
router.use(subscriptionsRouter);
router.use(giftsRouter);
router.use(messagesRouter);
router.use(communityRouter);

export default router;
